import assert from 'node:assert/strict';
import { CmaClient } from '@datocms/cli-utils';
import { isPortableCreationId } from '../../src/engine/portable-id';
import { fixtureId } from './fixture-id';

describe('portable creation identities', () => {
  it('accepts IDs generated by the public CMA SDK', () => {
    for (let index = 0; index < 100; index++) {
      assert.equal(isPortableCreationId(CmaClient.generateId()), true);
      assert.equal(isPortableCreationId(fixtureId(String(index))), true);
    }
  });

  it('rejects malformed lengths, alphabet, UUID versions and variants', () => {
    const valid = fixtureId('portable');
    const wrongVersion = Buffer.from(valid, 'base64url');
    wrongVersion[6] = (wrongVersion[6] & 0x0f) | 0x50;
    const wrongVariant = Buffer.from(valid, 'base64url');
    wrongVariant[8] &= 0x3f;
    for (const invalid of [
      '',
      valid.slice(1),
      `${valid}A`,
      `${valid}==`,
      `+${valid.slice(1)}`,
      `/${valid.slice(1)}`,
      ` ${valid.slice(1)}`,
      wrongVersion.toString('base64url'),
      wrongVariant.toString('base64url'),
      'A'.repeat(22),
    ]) {
      assert.equal(isPortableCreationId(invalid), false, invalid);
    }
  });

  it('rejects legacy numeric IDs including a 22-character zero-padded SDK-valid ID', () => {
    for (const legacy of ['123', '0000000000000000000123']) {
      assert.equal(CmaClient.isValidId(legacy), true);
      assert.equal(isPortableCreationId(legacy), false);
    }
  });

  it('rejects noncanonical base64 aliases for otherwise valid UUIDs', () => {
    const valid = fixtureId('canonical');
    const alphabet =
      'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
    const alias =
      valid.slice(0, -1) + alphabet[alphabet.indexOf(valid.at(-1)!) + 1];
    assert.equal(CmaClient.isValidId(alias), true);
    assert.deepEqual(
      Buffer.from(alias, 'base64url'),
      Buffer.from(valid, 'base64url'),
    );
    assert.equal(isPortableCreationId(alias), false);
  });
});
